/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luminary_os_core_Native */

#ifndef _Included_com_luminary_os_core_Native
#define _Included_com_luminary_os_core_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luminary_os_core_Native
 * Method:    getInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_luminary_os_core_Native_getInfo
  (JNIEnv *, jobject);

/*
 * Class:     Native
 * Method:    blacklistMethods
 * Signature: (Ljava/lang/Class;Ljava/util/Set;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_luminary_os_core_Native_blacklistMethods
  (JNIEnv *, jobject, jclass, jobject);
/*
 * Class:     Native
 * Method:    blacklistMethods
 * Signature: (Ljava/lang/Class;Ljava/util/Set;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_luminary_os_core_Native_blacklistFields
  (JNIEnv *, jobject, jclass, jobject);

/*
 * Class:     com_luminary_os_core_Native
 * Method:    calculateX
 * Signature: (III)F
 */
JNIEXPORT jfloat JNICALL Java_com_luminary_os_core_Native_calculateX
  (JNIEnv *, jobject, jint, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_luminary_os_core_Native
 * Method:    calculateY
 * Signature: (III)F
 */
JNIEXPORT jfloat JNICALL Java_com_luminary_os_core_Native_calculateY
  (JNIEnv *, jobject, jint, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_luminary_os_core_Native
 * Method:    calculateZ
 * Signature: (III)F
 */
JNIEXPORT jfloat JNICALL Java_com_luminary_os_core_Native_calculateZ
  (JNIEnv *, jobject, jint, jint, jint, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
